### ISSUE TITLE
Windows Binary Release missing node.dll & ffmpeg.dll

### ISSUE THREAD

**Issue by ColinMcNeil** [qawemlilo/nodetube-desktop#7]
Recieveing two errors preventing install:

"Node.dll is missing from your computer"
"FFMpeg.dll is missing from your computer"

I think you may not be including these in your build directory?

**Comment by qawemlilo** [comment]
Hi @ColinMcNeil , thank you for catching the error, I actually did the builds on osx and haven't done any tests on windows. Would appreciate it if someone could send me a fix for windows.

**Comment by ColinMcNeil** [comment]
The issue is that you are shipping just the executable. When I build on windows, it creates an entire folder with a bunch of files, all of which are necessary for the exe to run. I recommend making an installer to set up the folder, or just distribute a zip containing everything.
![image](https://user-images.githubusercontent.com/5000430/28886000-dd3d8e98-7785-11e7-837f-d36b1a57b04e.png)

**Comment by qawemlilo** [comment]
@ColinMcNeil Thank you for your help :)
